
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 03 13:43:19 CST 2018
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int clases = 37;
  public static final int asignmenos = 46;
  public static final int menos = 23;
  public static final int menor = 59;
  public static final int mod = 26;
  public static final int floaat = 78;
  public static final int verde = 51;
  public static final int comilla1 = 80;
  public static final int pto = 82;
  public static final int stringg = 68;
  public static final int corc = 84;
  public static final int cora = 83;
  public static final int booleann = 67;
  public static final int print = 76;
  public static final int anaranjado = 53;
  public static final int divhtml = 16;
  public static final int t10 = 99;
  public static final int azul = 50;
  public static final int title = 11;
  public static final int div = 25;
  public static final int morado = 54;
  public static final int body = 4;
  public static final int mas = 22;
  public static final int IDS = 81;
  public static final int cadena = 75;
  public static final int color = 55;
  public static final int head = 3;
  public static final int decimal = 77;
  public static final int dolar = 100;
  public static final int or = 33;
  public static final int score = 36;
  public static final int caracter = 30;
  public static final int comilla = 79;
  public static final int asignacion = 65;
  public static final int p = 17;
  public static final int id = 74;
  public static final int menorQ = 60;
  public static final int gris = 52;
  public static final int mayorQ = 62;
  public static final int asignpor = 47;
  public static final int br = 18;
  public static final int menosmenos = 44;
  public static final int textocolor = 56;
  public static final int truee = 71;
  public static final int hr = 19;
  public static final int table = 12;
  public static final int variables = 42;
  public static final int tr = 15;
  public static final int and = 32;
  public static final int cantidad = 41;
  public static final int mayor = 61;
  public static final int metodos = 40;
  public static final int derecha = 86;
  public static final int tdc = 89;
  public static final int centrado = 87;
  public static final int tda = 20;
  public static final int th = 13;
  public static final int EOF = 0;
  public static final int td = 14;
  public static final int amarillo = 49;
  public static final int doublee = 70;
  public static final int rojo = 48;
  public static final int font = 58;
  public static final int error = 1;
  public static final int izquierda = 85;
  public static final int html = 2;
  public static final int h6 = 10;
  public static final int h5 = 9;
  public static final int asignmas = 45;
  public static final int h4 = 8;
  public static final int distinto = 64;
  public static final int h3 = 7;
  public static final int h2 = 6;
  public static final int intt = 66;
  public static final int h1 = 5;
  public static final int parc = 28;
  public static final int por = 24;
  public static final int t9 = 98;
  public static final int para = 27;
  public static final int t8 = 97;
  public static final int t7 = 96;
  public static final int t6 = 95;
  public static final int t5 = 94;
  public static final int t4 = 93;
  public static final int t3 = 92;
  public static final int coma = 31;
  public static final int t2 = 91;
  public static final int t1 = 90;
  public static final int falsee = 72;
  public static final int charr = 69;
  public static final int not = 34;
  public static final int igual = 63;
  public static final int funciones = 38;
  public static final int align = 57;
  public static final int result = 35;
  public static final int thc = 88;
  public static final int masmas = 43;
  public static final int tha = 21;
  public static final int ctable = 101;
  public static final int num = 73;
  public static final int nombre = 39;
  public static final int ptoYcoma = 29;
}

