
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 31 23:10:27 CST 2018
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int asignmenos = 34;
  public static final int menos = 21;
  public static final int menor = 47;
  public static final int mod = 24;
  public static final int verde = 39;
  public static final int comilla1 = 67;
  public static final int stringg = 56;
  public static final int booleann = 55;
  public static final int print = 64;
  public static final int anaranjado = 41;
  public static final int divhtml = 16;
  public static final int t10 = 81;
  public static final int azul = 38;
  public static final int title = 11;
  public static final int div = 23;
  public static final int morado = 42;
  public static final int body = 4;
  public static final int mas = 20;
  public static final int cadena = 63;
  public static final int IDS = 68;
  public static final int color = 43;
  public static final int head = 3;
  public static final int decimal = 65;
  public static final int dolar = 82;
  public static final int or = 29;
  public static final int asignacion = 53;
  public static final int p = 17;
  public static final int comilla = 66;
  public static final int menorQ = 48;
  public static final int id = 62;
  public static final int gris = 40;
  public static final int mayorQ = 50;
  public static final int asignpor = 35;
  public static final int br = 18;
  public static final int menosmenos = 32;
  public static final int textocolor = 44;
  public static final int hr = 19;
  public static final int truee = 59;
  public static final int table = 12;
  public static final int tr = 15;
  public static final int and = 28;
  public static final int mayor = 49;
  public static final int derecha = 70;
  public static final int centrado = 71;
  public static final int th = 13;
  public static final int EOF = 0;
  public static final int td = 14;
  public static final int amarillo = 37;
  public static final int doublee = 58;
  public static final int rojo = 36;
  public static final int font = 46;
  public static final int error = 1;
  public static final int izquierda = 69;
  public static final int html = 2;
  public static final int h6 = 10;
  public static final int h5 = 9;
  public static final int asignmas = 33;
  public static final int h4 = 8;
  public static final int distinto = 52;
  public static final int h3 = 7;
  public static final int h2 = 6;
  public static final int intt = 54;
  public static final int h1 = 5;
  public static final int parc = 26;
  public static final int por = 22;
  public static final int t9 = 80;
  public static final int para = 25;
  public static final int t8 = 79;
  public static final int t7 = 78;
  public static final int t6 = 77;
  public static final int t5 = 76;
  public static final int t4 = 75;
  public static final int t3 = 74;
  public static final int t2 = 73;
  public static final int t1 = 72;
  public static final int charr = 57;
  public static final int falsee = 60;
  public static final int not = 30;
  public static final int igual = 51;
  public static final int align = 45;
  public static final int masmas = 31;
  public static final int num = 61;
  public static final int ptoYcoma = 27;
}

