
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 01 06:32:55 CST 2018
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int asignmenos = 36;
  public static final int menos = 21;
  public static final int menor = 49;
  public static final int mod = 24;
  public static final int floaat = 68;
  public static final int verde = 41;
  public static final int comilla1 = 70;
  public static final int stringg = 58;
  public static final int booleann = 57;
  public static final int print = 66;
  public static final int anaranjado = 43;
  public static final int divhtml = 16;
  public static final int t10 = 84;
  public static final int azul = 40;
  public static final int title = 11;
  public static final int div = 23;
  public static final int morado = 44;
  public static final int body = 4;
  public static final int mas = 20;
  public static final int IDS = 71;
  public static final int cadena = 65;
  public static final int color = 45;
  public static final int head = 3;
  public static final int decimal = 67;
  public static final int dolar = 85;
  public static final int or = 31;
  public static final int caracter = 28;
  public static final int asignacion = 55;
  public static final int p = 17;
  public static final int comilla = 69;
  public static final int menorQ = 50;
  public static final int id = 64;
  public static final int gris = 42;
  public static final int mayorQ = 52;
  public static final int asignpor = 37;
  public static final int br = 18;
  public static final int menosmenos = 34;
  public static final int textocolor = 46;
  public static final int hr = 19;
  public static final int truee = 61;
  public static final int table = 12;
  public static final int tr = 15;
  public static final int and = 30;
  public static final int mayor = 51;
  public static final int derecha = 73;
  public static final int centrado = 74;
  public static final int th = 13;
  public static final int EOF = 0;
  public static final int td = 14;
  public static final int amarillo = 39;
  public static final int doublee = 60;
  public static final int rojo = 38;
  public static final int font = 48;
  public static final int error = 1;
  public static final int izquierda = 72;
  public static final int html = 2;
  public static final int h6 = 10;
  public static final int h5 = 9;
  public static final int asignmas = 35;
  public static final int h4 = 8;
  public static final int distinto = 54;
  public static final int h3 = 7;
  public static final int h2 = 6;
  public static final int intt = 56;
  public static final int h1 = 5;
  public static final int parc = 26;
  public static final int por = 22;
  public static final int t9 = 83;
  public static final int para = 25;
  public static final int t8 = 82;
  public static final int t7 = 81;
  public static final int t6 = 80;
  public static final int t5 = 79;
  public static final int t4 = 78;
  public static final int t3 = 77;
  public static final int coma = 29;
  public static final int t2 = 76;
  public static final int t1 = 75;
  public static final int charr = 59;
  public static final int falsee = 62;
  public static final int not = 32;
  public static final int igual = 53;
  public static final int align = 47;
  public static final int masmas = 33;
  public static final int num = 63;
  public static final int ptoYcoma = 27;
}

