/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compi1_usuario;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ale
 */
public class FrmPrincipal extends javax.swing.JFrame {

    Archivo miArchivo = new Archivo();
    JEditorPane nuevaHoja;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        this.setLayout(null);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        PanelPest = new javax.swing.JTabbedPane();
        Panel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCont = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListCompoL = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        lblProducciones = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuAbrir = new javax.swing.JMenuItem();
        MenuNuevo = new javax.swing.JMenuItem();
        MenuGuardar = new javax.swing.JMenuItem();
        MenuGuardarC = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        MenuAnalizar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuReporteTokens = new javax.swing.JMenuItem();
        MenuReporteErrores = new javax.swing.JMenuItem();
        MenuUbiacion = new javax.swing.JMenu();
        MenuSalidahtml = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuUbiacion1 = new javax.swing.JMenu();
        MenuManualUsuario = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Desktop.background"));
        getContentPane().setLayout(null);

        jScrollPane4.setViewportView(txtCont);

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        PanelPest.addTab("tab1", Panel1);

        ListCompoL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListCompoLMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListCompoL);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Componentes Lexicos");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        lblProducciones.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblProducciones.setForeground(new java.awt.Color(0, 204, 204));
        lblProducciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducciones.setText("Automata");
        lblProducciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(PanelPest, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProducciones, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblProducciones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(PanelPest, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Escritorio);
        Escritorio.setBounds(10, 10, 870, 580);

        jMenu1.setBackground(new java.awt.Color(24, 240, 240));
        jMenu1.setText("Archivo");
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 15)); // NOI18N

        MenuAbrir.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 13)); // NOI18N
        MenuAbrir.setText("Abrir");
        MenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAbrir);

        MenuNuevo.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 13)); // NOI18N
        MenuNuevo.setText("Nuevo");
        MenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuNuevo);

        MenuGuardar.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 13)); // NOI18N
        MenuGuardar.setLabel("Guardar");
        MenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(MenuGuardar);

        MenuGuardarC.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 13)); // NOI18N
        MenuGuardarC.setText("Guardar Como");
        MenuGuardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGuardarCActionPerformed(evt);
            }
        });
        jMenu1.add(MenuGuardarC);

        MenuSalir.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 13)); // NOI18N
        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSalir);
        jMenu1.add(jSeparator1);
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Analizador");
        jMenu2.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 15)); // NOI18N

        MenuAnalizar.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 13)); // NOI18N
        MenuAnalizar.setText("Analizador");
        MenuAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAnalizarActionPerformed(evt);
            }
        });
        jMenu2.add(MenuAnalizar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");
        jMenu3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 15)); // NOI18N

        MenuReporteTokens.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 13)); // NOI18N
        MenuReporteTokens.setText("Tokens");
        MenuReporteTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReporteTokensActionPerformed(evt);
            }
        });
        jMenu3.add(MenuReporteTokens);

        MenuReporteErrores.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 13)); // NOI18N
        MenuReporteErrores.setText("Errores");
        MenuReporteErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReporteErroresActionPerformed(evt);
            }
        });
        jMenu3.add(MenuReporteErrores);

        jMenuBar1.add(jMenu3);

        MenuUbiacion.setText("Ver");
        MenuUbiacion.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 15)); // NOI18N

        MenuSalidahtml.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 13)); // NOI18N
        MenuSalidahtml.setText("HTML");
        MenuSalidahtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalidahtmlActionPerformed(evt);
            }
        });
        MenuUbiacion.add(MenuSalidahtml);

        jMenuItem2.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 13)); // NOI18N
        jMenuItem2.setText("Ubicacion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuUbiacion.add(jMenuItem2);

        jMenuBar1.add(MenuUbiacion);

        MenuUbiacion1.setText("Manuales");
        MenuUbiacion1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 15)); // NOI18N

        MenuManualUsuario.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 13)); // NOI18N
        MenuManualUsuario.setText("Usuario");
        MenuManualUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuManualUsuarioActionPerformed(evt);
            }
        });
        MenuUbiacion1.add(MenuManualUsuario);

        jMenuItem3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 13)); // NOI18N
        jMenuItem3.setText("Tecnico");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuUbiacion1.add(jMenuItem3);

        jMenuBar1.add(MenuUbiacion1);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 908, 657);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAbrirActionPerformed
        //verifica si el cuadro de texto esta vacio
        if (txtCont.getText().length() <= 0) {
            abrirArchivo();
        } else if ((txtCont.getText().length() > 0)) {
            nuevoArchivo();
            try {
                Thread.sleep(1500);
            } catch (InterruptedException ex) {
                //   Logger.getLogger(Form_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            abrirArchivo();
        }

    }//GEN-LAST:event_MenuAbrirActionPerformed

    public void nuevoArchivo() {

//        int answer = JOptionPane.showConfirmDialog(null, "¿Desea Guardar los cambios?", " EcysWeb ", JOptionPane.YES_NO_OPTION, 2, icono);
//        if (answer == JOptionPane.YES_OPTION) {
//            try {
//                if (miArchivo.getPath() != null) {
//                    guardar();
//                    limpiarContenido();
//                } else {
//                    GuardarComo();
//                    limpiarContenido();
//                }
//            } catch (Exception e) {
//                System.out.println(e);
//            }
//        } else if (answer == JOptionPane.NO_OPTION) {
//            txtCont.setText("");
//            txtCont.setText(" ");
//            miArchivo.setContenido("");
//        }
    }


    private void MenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNuevoActionPerformed
        crearPag();
    }//GEN-LAST:event_MenuNuevoActionPerformed

    private void MenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGuardarActionPerformed
        guardar();

    }//GEN-LAST:event_MenuGuardarActionPerformed

    private void MenuGuardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGuardarCActionPerformed
    }//GEN-LAST:event_MenuGuardarCActionPerformed

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void MenuAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAnalizarActionPerformed
       JinternalAnalizador p1 = new JinternalAnalizador();
       p1.setSize(863,350);
       p1.setLocation(4,0);
       Escritorio.add(p1);
       p1.show();
 
    }//GEN-LAST:event_MenuAnalizarActionPerformed

    private void MenuReporteTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReporteTokensActionPerformed
    }//GEN-LAST:event_MenuReporteTokensActionPerformed

    private void MenuReporteErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReporteErroresActionPerformed

    }//GEN-LAST:event_MenuReporteErroresActionPerformed

    private void MenuSalidahtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalidahtmlActionPerformed

    }//GEN-LAST:event_MenuSalidahtmlActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed


    private void MenuManualUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuManualUsuarioActionPerformed


    }//GEN-LAST:event_MenuManualUsuarioActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed


    }//GEN-LAST:event_jMenuItem3ActionPerformed


    private void ListCompoLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListCompoLMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_ListCompoLMouseClicked

    /**
     * @param args the command line arguments
     */
    
     public JEditorPane crearPag() {
        JPanel pag = new JPanel();
        pag.setLayout(null);
        JEditorPane nv = new JEditorPane();
        nv.setBounds(15, 15, 460, 515);
        nv.setVisible(true);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("salir.png"));

        Panel1.add(nv);
        pag.add(nv);
        PanelPest.addTab("New", icon, pag, "Salir");
        nuevaHoja = nv;
        return nv;
    }
    
    public void guardar() {
        try (FileWriter fw = new FileWriter(miArchivo.getPath())) {
            //Escribimos el texto en el fichero
            fw.write(txtCont.getText());
            miArchivo.setContenido(txtCont.getText());
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }

    public void abrirArchivo() {
        //objeto que permite acceder al fichero
        JFileChooser SelecArchivo = new JFileChooser();
        FileNameExtensionFilter FiltExt = new FileNameExtensionFilter("Select File", "cp");
        SelecArchivo.setFileFilter(FiltExt);

        int seleccion = SelecArchivo.showOpenDialog(null);
        //seleccionamos el archivo
        if (seleccion == JFileChooser.APPROVE_OPTION) {

            try {
                //Selecciona la ruta del fichero
                File archivo = SelecArchivo.getSelectedFile();
                miArchivo.setPath(archivo.getAbsolutePath());
                miArchivo.setNombre(archivo.getName());
                miArchivo.setPathPadre(archivo.getParent());
                leerArchivo(archivo);
            } catch (Exception e1) {
                e1.printStackTrace();
            }
        }
    }

    int contadorHojas = 0;

    public void leerArchivo(File archivo) {
        try (FileReader fr = new FileReader(archivo)) {
            String cadena = "";
            int valor = fr.read();
            while (valor != -1) {
                cadena = cadena + (char) valor;
                valor = fr.read();
            }

            if (contadorHojas == 0) {
                miArchivo.setContenido(cadena);
                txtCont.setText(miArchivo.getContenido());
                contadorHojas++;
            } else {
                nuevaHoja.setText(cadena);

            }
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JList<String> ListCompoL;
    private javax.swing.JMenuItem MenuAbrir;
    private javax.swing.JMenuItem MenuAnalizar;
    private javax.swing.JMenuItem MenuGuardar;
    private javax.swing.JMenuItem MenuGuardarC;
    private javax.swing.JMenuItem MenuManualUsuario;
    private javax.swing.JMenuItem MenuNuevo;
    private javax.swing.JMenuItem MenuReporteErrores;
    private javax.swing.JMenuItem MenuReporteTokens;
    private javax.swing.JMenuItem MenuSalidahtml;
    private javax.swing.JMenuItem MenuSalir;
    private javax.swing.JMenu MenuUbiacion;
    private javax.swing.JMenu MenuUbiacion1;
    private javax.swing.JPanel Panel1;
    private javax.swing.JTabbedPane PanelPest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblProducciones;
    private javax.swing.JTextPane txtCont;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

}
